puts " "
puts " "
puts " You need to know and be able to do the following: "
puts " (1): string interpolation"
puts " (2): variables and data types"
puts " (3): transform data types"
puts " (4): methods, arguments, and calling a method"
puts " (5): input/output"
puts " (6): Control Flow"
puts " (7): Computer structure and command line"
puts " (8): Nesting"
puts " (9): Truth Tables & Logic gates"
puts " (10): Abstraction "
puts " "
puts " "

puts " Test = 50 percent"
puts " Project = 50 percent"
puts " "
